alias home_proxy='ssh -D localhost:8080 root@cloud.thestrangeland.net' 
alias ll='ls -la'
alias svim='sudo vim'
alias reddit='rtv'
alias ttyclock='tty-clock -ct'

alias pac='yaourt -S'
alias pacs='yaourt -Ss'
alias pacr='sudo pacman -Rsc'
alias pacup='yaourt -Syu'
alias pacsync='yaourt -Syy'
