" Matty .vimrc


" colors {{{
	syntax enable		"allow syntax highlighting
	colorscheme desert	" set interface colorscheme
" }}}

" misc {{{
	set ttyfast         "speeds scrolling
    set lines=40 columns=140    "sets window size
    set laststatus=2    "displays airline.vim persistantly
"    set spell spelllang=en_us   "check spelling while you type
    set tw=80
	
" }}}

" spaces and tabs {{{
	set tabstop=4 		"nmbr of visual spaces per TAB
	set softtabstop=4 	"nmbr of spaces per TAB when editing
	set expandtab		"tabs are spaces
" }}}

" UI config {{{
	set number		"show line numbers
	set showcmd		"show last command in bottom line
	set cursorline		"show current line
	filetype indent on	"load filetype-specific indent files
	set wildmenu		"visual autocomplete for command line
	set lazyredraw		"only redraw when we need to
	set showmatch		"highlight matching [{(]})
    set ruler
    set showcmd
    set autoindent		" always set autoindenting on
" }}}

" searching {{{
	set incsearch		"search while typing
	set hlsearch		"highlight search

	"turn off search highlighting
	nnoremap <leader><space> :nohlsearch<CR>
	
" }}}


" launch config {{{
"	call pathogen#infect()   "use pathogen
	set nocompatible
" }}}
